source 'https://rubygems.org'

gem 'rails', '3.2.14'

gem 'pg'

gem 'bcrypt'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'


group :development, :testing  do
  gem 'rspec-rails'
end

group :testing do
  gem 'faker'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
  gem 'selenium-webdriver'
  gem 'capybara'
end


gem 'debugger'
